export const watches = [
  {
    id: 1,
    name: "DAY-DATE 40",
    description: "Oyster, 40 mm, platinum",
    price: 100000,
    img: "/images/Screenshot_1.png",
    numberOfUnits: 1,
    category: "Classic",
    darkImg: "/images/Screenshot_1_Dark.png",
    variation: "/images/variation_1.png",
  },
  {
    id: 2,
    name: "DATEJUST 36",
    description: "Oyster, 36 mm, Oystersteel and yellow gold",
    price: 85000,
    img: "/images/Screenshot_2.png",
    numberOfUnits: 1,
    category: "Classic",
    darkImg: "/images/Screenshot_2_Dark.png",
    variation: "/images/variation_2.png",
  },
  {
    id: 3,
    name: "OYSTER PERPETUAL 41",
    description: "Oyster, 41 mm, Oystersteel",
    price: 80000,
    img: "/images/Screenshot_10.png",
    numberOfUnits: 1,
    category: "Classic",
    darkImg: "/images/Screenshot_10_Dark.png",
    variation: "/images/variation_10.png",
  },
  {
    id: 4,
    name: "LADY-DATEJUST 28",
    description: "Oyster, 28 mm, yellow gold",
    price: 82000,
    img: "/images/Screenshot_9.png",
    numberOfUnits: 1,
    category: "Classic",
    darkImg: "/images/Screenshot_9_Dark.png",
    variation: "/images/variation_9.png",
  },
  {
    id: 5,
    name: "SKY-DWELLER",
    description: "Oyster, 42 mm, yellow gold",
    price: 75000,
    img: "/images/Screenshot_8.png",
    numberOfUnits: 1,
    category: "Classic",
    darkImg: "/images/Screenshot_8_Dark.png",
    variation: "/images/variation_8.png",
  },
  {
    id: 6,
    name: "CELLINI",
    description: "39 mm, 18 kt Everose gold, polished finish",
    price: 100000,
    img: "/images/Screenshot_7.png",
    numberOfUnits: 1,
    category: "Classic",
    darkImg: "/images/Screenshot_7_Dark.png",
    variation: "/images/variation_10.png",
  },
  {
    id: 7,
    name: "AIR-KING",
    description: "Oyster, 40 mm, Oystersteel",
    price: 65000,
    img: "/images/Screenshot_6.png",
    numberOfUnits: 1,
    category: "Professional",
    darkImg: "/images/Screenshot_6_Dark.png",
    variation: "/images/variation_10.png",
  },
  {
    id: 8,
    name: "SUBMARINER",
    description: "Oyster, 41 mm, Oystersteel",
    price: 70000,
    img: "/images/Screenshot_5.png",
    numberOfUnits: 1,
    category: "Professional",
    darkImg: "/images/Screenshot_5_Dark.png",
    variation: "/images/variation_10.png",
  },
  {
    id: 9,
    name: "COSMOGRAPH DAYTONA",
    description: "Oyster, 40 mm, yellow gold",
    price: 60000,
    img: "/images/Screenshot_3.png",
    numberOfUnits: 1,
    category: "Professional",
    darkImg: "/images/Screenshot_3_Dark.png",
    variation: "/images/variation_3.png",
  },
  {
    id: 10,
    name: "EXPLORER",
    description: "Oyster, 36 mm, Oystersteel and yellow gold",
    price: 50000,
    img: "/images/Screenshot_4.png",
    numberOfUnits: 1,
    category: "Professional",
    darkImg: "/images/Screenshot_4_Dark.png",
    variation: "/images/variation_10.png",
  },
];
